USE [master]
GO

/****** Object:  Database [Prac1]    Script Date: 27/02/2019 06:56:40 p. m. ******/
CREATE DATABASE [Prac1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Prac1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Prac1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Prac1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Prac1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Prac1] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Prac1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Prac1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Prac1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Prac1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Prac1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Prac1] SET ARITHABORT OFF 
GO

ALTER DATABASE [Prac1] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Prac1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Prac1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Prac1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Prac1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Prac1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Prac1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Prac1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Prac1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Prac1] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Prac1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Prac1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Prac1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Prac1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Prac1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Prac1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Prac1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Prac1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Prac1] SET  MULTI_USER 
GO

ALTER DATABASE [Prac1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Prac1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Prac1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Prac1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Prac1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Prac1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Prac1] SET  READ_WRITE 
GO

